language: c

sudo: false

addons:
  apt:
    packages:
      - lcov
      - llvm-3.9-dev
      - cmake

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

script:
  - case "$CC" in "" | *gcc*) cmake -DULANG_USE_GCOV=ON .;; *) cmake -DULANG_USE_GCOV=OFF .;; esac
  - case "$CC" in "" | *gcc*) make coverage;; *) make check;; esac
