language: c

sudo: false

addons:
  apt:
    packages:
      - lcov
      - llvm-3.9-dev
      - cmake

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -DULANG_USE_GCOV=ON .
  - make coverage

after_success:
  - coveralls --exclude tests --exclude third-party --gcov-options '\-lp'
