language: c

sudo: false

addons:
  apt:
    packages:
      - lcov
      - llvm-3.9-dev
      - cmake

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls

script:
  - case "$CC" in "" | *gcc*) cmake -DULANG_USE_GCOV=ON .;; *) cmake -DULANG_USE_GCOV=OFF .;; esac
  - case "$CC" in "" | *gcc*) make coverage;; *) make check;; esac

after_success:
  - case "$CC" in "" | *gcc*) coveralls -b $(pwd) -i lib -i src --exclude tests --exclude third-party --exclude CMakeFiles --gcov-options '\-lp';; *) echo Skipped coverage reports;; esac
