language: c

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - llvm-3.9-dev
      - cmake
      - g++-4.9

compiler:
  - gcc
  - clang

before_install:
  - case "$CC" in "" | *gcc*) CC=gcc-4.9 && CXX=g++-4.9;; esac
  - pip install --user cpp-coveralls

script:
  - case "$CC" in "" | *gcc*) cmake -DULANG_USE_GCOV=ON .;; *) cmake -DULANG_USE_GCOV=OFF .;; esac
  - case "$CC" in "" | *gcc*) make coverage;; *) make check;; esac
